apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: flask-k8s-secret-status
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: hello@devopscoder.io
  lifecycle: development
